/**
 * The curriculum is authored here, not derived from a dictionary: the choice
 * of which words a child learns first is a teaching decision. The drafter
 * looks each English word up in the lexicon and proposes Oromo answers for a
 * fluent speaker to confirm.
 */
export interface UnitSpec {
  id: string;
  order: number;
  title: string;
  /** English prompts, in teaching order. `pos` narrows lexicon candidates. */
  words: { english: string; pos: "noun" | "verb" | "adj" | "num" }[];
}

type Pos = UnitSpec["words"][number]["pos"];

const of = (pos: Pos) =>
  (...words: string[]): UnitSpec["words"] =>
    words.map((english) => ({ english, pos }));

const nouns = of("noun");
const verbs = of("verb");
const adjectives = of("adj");
const numbers = of("num");

export const UNITS: UnitSpec[] = [
  {
    id: "unit-01-family",
    order: 1,
    title: "Family",
    words: nouns(
      "mother",
      "father",
      "child",
      "baby",
      "brother",
      "sister",
      "son",
      "daughter",
      "grandmother",
      "grandfather",
      "family",
      "boy",
      "girl",
      "man",
      "woman",
      "friend",
      "name",
      "home",
      "husband",
      "wife",
      "uncle",
      "aunt",
      "people",
      "neighbor",
      "guest",
    ),
  },
  {
    id: "unit-02-food-and-drink",
    order: 2,
    title: "Food & drink",
    words: [
      ...nouns(
        "water",
        "milk",
        "coffee",
        "tea",
        "bread",
        "meat",
        "egg",
        "salt",
        "sugar",
        "butter",
        "honey",
        "food",
        "fruit",
        "banana",
        "orange",
        "onion",
        "potato",
        "maize",
        "barley",
        "porridge",
        "cup",
        "plate",
        "spoon",
      ),
      ...verbs("eat", "drink"),
    ],
  },
  {
    id: "unit-03-animals",
    order: 3,
    title: "Animals",
    words: nouns(
      "dog",
      "cat",
      "cow",
      "ox",
      "goat",
      "sheep",
      "horse",
      "donkey",
      "camel",
      "chicken",
      "bird",
      "fish",
      "lion",
      "elephant",
      "monkey",
      "snake",
      "mouse",
      "hyena",
      "leopard",
      "buffalo",
      "bee",
      "fly",
      "hen",
      "calf",
      "animal",
    ),
  },
  {
    id: "unit-04-numbers",
    order: 4,
    title: "Numbers & counting",
    words: [
      ...numbers(
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "twenty",
        "thirty",
        "fifty",
        "hundred",
        "thousand",
        "first",
        "second",
        "third",
      ),
      ...nouns("number", "half"),
      ...adjectives("many", "few"),
      ...verbs("count"),
    ],
  },
  {
    id: "unit-05-colours-and-sizes",
    order: 5,
    title: "Colours & sizes",
    words: [
      ...adjectives(
        "red",
        "white",
        "black",
        "green",
        "yellow",
        "blue",
        "brown",
        "grey",
        "big",
        "small",
        "long",
        "short",
        "tall",
        "wide",
        "narrow",
        "heavy",
        "light",
        "new",
        "old",
        "hot",
        "cold",
        "clean",
        "dirty",
      ),
      ...nouns("colour", "size"),
    ],
  },
  {
    id: "unit-06-feelings-and-doing",
    order: 6,
    title: "Feelings & doing",
    words: [
      ...adjectives(
        "happy",
        "sad",
        "angry",
        "tired",
        "hungry",
        "thirsty",
        "sick",
        "afraid",
        "good",
        "bad",
      ),
      ...verbs(
        "play",
        "sleep",
        "run",
        "walk",
        "sit",
        "stand",
        "come",
        "go",
        "speak",
        "hear",
        "see",
        "read",
        "write",
        "laugh",
        "cry",
      ),
    ],
  },
  {
    id: "unit-07-body",
    order: 7,
    title: "Body",
    words: nouns(
      "head",
      "hair",
      "eye",
      "ear",
      "nose",
      "mouth",
      "tooth",
      "tongue",
      "lip",
      "neck",
      "shoulder",
      "arm",
      "hand",
      "finger",
      "nail",
      "chest",
      "heart",
      "back",
      "stomach",
      "belly",
      "leg",
      "knee",
      "foot",
      "toe",
      "skin",
    ),
  },
  {
    id: "unit-08-health",
    order: 8,
    title: "Health & feeling unwell",
    words: nouns(
      "illness",
      "pain",
      "fever",
      "cough",
      "wound",
      "medicine",
      "doctor",
      "hospital",
      "nurse",
      "blood",
      "health",
      "sneeze",
      "headache",
      "thirst",
      "hunger",
      "dream",
      "scar",
      "sickness",
      "cure",
      "vomit",
      "injury",
      "swelling",
      "itch",
      "death",
      "life",
    ),
  },
  {
    id: "unit-09-clothes",
    order: 9,
    title: "Clothes",
    words: nouns(
      "clothes",
      "shirt",
      "trousers",
      "dress",
      "skirt",
      "shoe",
      "hat",
      "cap",
      "belt",
      "coat",
      "blanket",
      "cloth",
      "cotton",
      "wool",
      "button",
      "pocket",
      "ring",
      "necklace",
      "bracelet",
      "earring",
      "needle",
      "thread",
      "scarf",
      "towel",
      "bead",
    ),
  },
  {
    id: "unit-10-house",
    order: 10,
    title: "House & home",
    words: nouns(
      "house",
      "door",
      "window",
      "roof",
      "wall",
      "floor",
      "room",
      "bed",
      "chair",
      "table",
      "lamp",
      "key",
      "fence",
      "gate",
      "yard",
      "kitchen",
      "garden",
      "stairs",
      "shelf",
      "box",
      "basket",
      "bag",
      "broom",
      "mat",
      "curtain",
    ),
  },
  {
    id: "unit-11-kitchen",
    order: 11,
    title: "Kitchen & utensils",
    words: nouns(
      "pot",
      "pan",
      "knife",
      "fork",
      "bowl",
      "bottle",
      "jug",
      "kettle",
      "lid",
      "cover",
      "firewood",
      "oven",
      "flour",
      "oil",
      "cheese",
      "spice",
      "pepper",
      "soup",
    ),
  },
  {
    id: "unit-12-school",
    order: 12,
    title: "School & learning",
    words: nouns(
      "school",
      "teacher",
      "student",
      "book",
      "page",
      "pen",
      "pencil",
      "paper",
      "letter",
      "word",
      "question",
      "answer",
      "lesson",
      "story",
      "song",
      "language",
      "chalk",
      "class",
      "library",
      "pupil",
      "knowledge",
      "writing",
      "reading",
      "game",
      "rule",
    ),
  },
  {
    id: "unit-13-time",
    order: 13,
    title: "Time, days & seasons",
    words: nouns(
      "time",
      "day",
      "night",
      "morning",
      "evening",
      "afternoon",
      "week",
      "month",
      "year",
      "today",
      "tomorrow",
      "hour",
      "minute",
      "season",
      "summer",
      "winter",
      "spring",
      "autumn",
      "rain",
      "sun",
      "moon",
      "star",
      "sky",
      "dawn",
      "dusk",
    ),
  },
  {
    id: "unit-14-weather",
    order: 14,
    title: "Weather & sky",
    words: nouns(
      "wind",
      "cloud",
      "storm",
      "thunder",
      "lightning",
      "heat",
      "ice",
      "fog",
      "dew",
      "rainbow",
      "shade",
      "drought",
      "flood",
      "mud",
      "dust",
      "smoke",
      "air",
      "darkness",
      "frost",
      "weather",
    ),
  },
  {
    id: "unit-15-nature",
    order: 15,
    title: "Land & water",
    words: nouns(
      "land",
      "mountain",
      "hill",
      "valley",
      "river",
      "stream",
      "lake",
      "sea",
      "well",
      "stone",
      "rock",
      "sand",
      "soil",
      "forest",
      "field",
      "farm",
      "road",
      "path",
      "bridge",
      "cave",
      "island",
      "shore",
      "desert",
      "grass",
      "hole",
    ),
  },
  {
    id: "unit-16-plants",
    order: 16,
    title: "Trees & plants",
    words: nouns(
      "tree",
      "leaf",
      "branch",
      "root",
      "flower",
      "seed",
      "bush",
      "thorn",
      "bark",
      "wood",
      "trunk",
      "plant",
      "crop",
      "weed",
      "stem",
      "shoot",
      "vine",
      "bamboo",
      "palm",
      "cactus",
      "moss",
      "pollen",
    ),
  },
  {
    id: "unit-17-fruit",
    order: 17,
    title: "Fruit & vegetables",
    words: nouns(
      "lemon",
      "mango",
      "apple",
      "papaya",
      "pineapple",
      "tomato",
      "garlic",
      "cabbage",
      "carrot",
      "pumpkin",
      "bean",
      "pea",
      "corn",
      "wheat",
      "sorghum",
      "rice",
      "spinach",
      "melon",
    ),
  },
  {
    id: "unit-18-cooking",
    order: 18,
    title: "Cooking & meals",
    words: nouns(
      "meal",
      "lunch",
      "supper",
      "dinner",
      "stew",
      "sauce",
      "dough",
      "juice",
      "beer",
      "taste",
      "cream",
      "fat",
      "broth",
      "mash",
      "slice",
      "loaf",
      "grain",
      "husk",
      "peel",
      "yeast",
      "portion",
      "leftovers",
      "feast",
      "snack",
      "cake",
    ),
  },
  {
    id: "unit-19-livestock",
    order: 19,
    title: "Farm animals",
    words: nouns(
      "bull",
      "lamb",
      "mule",
      "rooster",
      "chick",
      "pig",
      "rabbit",
      "herd",
      "cattle",
      "horn",
      "hoof",
      "shepherd",
      "barn",
      "pasture",
      "manure",
      "fodder",
      "graze",
      "kid",
      "ewe",
      "ram",
      "stallion",
      "mare",
      "flock",
      "cage",
      "saddle",
    ),
  },
  {
    id: "unit-20-wild-animals",
    order: 20,
    title: "Wild animals",
    words: nouns(
      "giraffe",
      "zebra",
      "baboon",
      "antelope",
      "gazelle",
      "rhinoceros",
      "hippopotamus",
      "crocodile",
      "lizard",
      "frog",
      "fox",
      "jackal",
      "wolf",
      "bear",
      "deer",
      "porcupine",
      "squirrel",
      "bat",
      "rat",
      "mole",
    ),
  },
  {
    id: "unit-21-birds",
    order: 21,
    title: "Birds",
    words: nouns(
      "duck",
      "goose",
      "dove",
      "pigeon",
      "crow",
      "eagle",
      "hawk",
      "vulture",
      "owl",
      "ostrich",
      "stork",
      "parrot",
      "sparrow",
      "swallow",
      "nest",
      "wing",
      "feather",
      "beak",
      "claw",
      "tail",
      "flight",
      "heron",
      "falcon",
    ),
  },
  {
    id: "unit-22-insects",
    order: 22,
    title: "Insects & small creatures",
    words: nouns(
      "insect",
      "mosquito",
      "wasp",
      "ant",
      "termite",
      "spider",
      "web",
      "scorpion",
      "butterfly",
      "locust",
      "grasshopper",
      "beetle",
      "worm",
      "snail",
      "flea",
      "louse",
      "tick",
      "caterpillar",
      "cricket",
      "sting",
      "larva",
    ),
  },
  {
    id: "unit-23-market",
    order: 23,
    title: "Market & money",
    words: nouns(
      "market",
      "money",
      "price",
      "shop",
      "trade",
      "coin",
      "silver",
      "gold",
      "change",
      "debt",
      "loan",
      "profit",
      "loss",
      "wealth",
      "poverty",
      "scale",
      "weight",
      "measure",
      "sack",
      "customer",
      "goods",
      "work",
      "wage",
      "tax",
      "gift",
    ),
  },
  {
    id: "unit-24-town",
    order: 24,
    title: "Town & buildings",
    words: nouns(
      "town",
      "city",
      "village",
      "street",
      "church",
      "mosque",
      "office",
      "hotel",
      "station",
      "bank",
      "post",
      "prison",
      "court",
      "palace",
      "square",
      "building",
      "camp",
      "compound",
    ),
  },
  {
    id: "unit-25-travel",
    order: 25,
    title: "Travel & transport",
    words: nouns(
      "journey",
      "car",
      "bus",
      "truck",
      "bicycle",
      "wheel",
      "cart",
      "train",
      "boat",
      "ship",
      "canoe",
      "ticket",
      "passenger",
      "distance",
      "direction",
      "map",
      "speed",
      "stop",
      "departure",
    ),
  },
  {
    id: "unit-26-work",
    order: 26,
    title: "Work & jobs",
    words: nouns(
      "farmer",
      "soldier",
      "police",
      "judge",
      "king",
      "queen",
      "chief",
      "servant",
      "guard",
      "fisherman",
      "blacksmith",
      "carpenter",
      "tailor",
      "weaver",
      "potter",
      "singer",
      "priest",
      "leader",
      "helper",
      "worker",
      "cook",
      "baker",
    ),
  },
  {
    id: "unit-27-tools",
    order: 27,
    title: "Tools & materials",
    words: nouns(
      "tool",
      "axe",
      "hoe",
      "rope",
      "string",
      "hammer",
      "saw",
      "stick",
      "spear",
      "bow",
      "arrow",
      "shield",
      "gun",
      "net",
      "trap",
      "plough",
      "yoke",
      "iron",
      "metal",
      "glass",
      "clay",
      "leather",
      "plastic",
    ),
  },
  {
    id: "unit-28-culture",
    order: 28,
    title: "Music, story & celebration",
    words: nouns(
      "music",
      "drum",
      "flute",
      "dance",
      "riddle",
      "proverb",
      "poem",
      "wedding",
      "funeral",
      "ceremony",
      "blessing",
      "prayer",
      "god",
      "spirit",
      "custom",
      "tradition",
      "clan",
      "elder",
      "holiday",
    ),
  },
  {
    id: "unit-29-verbs-move",
    order: 29,
    title: "Verbs: moving",
    words: verbs(
      "jump",
      "climb",
      "fall",
      "lie",
      "enter",
      "leave",
      "return",
      "arrive",
      "follow",
      "flee",
      "carry",
      "bring",
      "send",
      "push",
      "pull",
      "turn",
      "cross",
      "swim",
      "ride",
      "pass",
      "wait",
      "hurry",
      "travel",
      "crawl",
    ),
  },
  {
    id: "unit-30-verbs-speak",
    order: 30,
    title: "Verbs: speaking & thinking",
    words: verbs(
      "say",
      "tell",
      "ask",
      "call",
      "shout",
      "whisper",
      "sing",
      "think",
      "know",
      "understand",
      "remember",
      "forget",
      "learn",
      "teach",
      "believe",
      "want",
      "hope",
      "fear",
      "love",
      "hate",
      "decide",
      "promise",
      "greet",
      "thank",
      "pray",
    ),
  },
  {
    id: "unit-31-verbs-hands",
    order: 31,
    title: "Verbs: hands & making",
    words: verbs(
      "take",
      "give",
      "hold",
      "put",
      "open",
      "close",
      "tie",
      "cut",
      "break",
      "build",
      "make",
      "dig",
      "sow",
      "harvest",
      "grind",
      "pound",
      "sew",
      "weave",
      "wash",
      "sweep",
      "bake",
      "boil",
      "fill",
      "pour",
      "throw",
    ),
  },
  {
    id: "unit-32-verbs-body",
    order: 32,
    title: "Verbs: body & senses",
    words: verbs(
      "wake",
      "listen",
      "smell",
      "touch",
      "feel",
      "breathe",
      "bite",
      "chew",
      "spit",
      "bathe",
      "rest",
      "die",
      "grow",
      "heal",
      "yawn",
      "blink",
      "shiver",
      "sweat",
      "tremble",
      "kneel",
      "bend",
      "stretch",
      "swell",
      "bleed",
      "faint",
    ),
  },
  {
    id: "unit-33-verbs-daily",
    order: 33,
    title: "Verbs: everyday life",
    words: verbs(
      "help",
      "buy",
      "sell",
      "pay",
      "borrow",
      "lend",
      "keep",
      "find",
      "lose",
      "search",
      "choose",
      "share",
      "divide",
      "add",
      "begin",
      "finish",
      "try",
      "use",
      "need",
      "show",
      "hide",
      "meet",
      "visit",
      "live",
      "stay",
    ),
  },
  {
    id: "unit-34-adjectives",
    order: 34,
    title: "Describing things",
    words: adjectives(
      "young",
      "large",
      "strong",
      "weak",
      "full",
      "empty",
      "warm",
      "sweet",
      "bitter",
      "sour",
      "soft",
      "hard",
      "fast",
      "slow",
      "beautiful",
      "ugly",
      "rich",
      "poor",
      "easy",
      "difficult",
    ),
  },
  {
    id: "unit-35-people",
    order: 35,
    title: "People & community",
    words: nouns(
      "person",
      "youth",
      "stranger",
      "neighbour",
      "enemy",
      "tribe",
      "nation",
      "relative",
      "orphan",
      "widow",
      "bride",
      "groom",
      "twin",
      "group",
      "citizen",
      "ancestor",
      "descendant",
      "generation",
      "age",
      "couple",
      "company",
      "assembly",
      "meeting",
      "quarrel",
      "agreement",
    ),
  },
  {
    id: "unit-36-directions",
    order: 36,
    title: "Places & directions",
    words: nouns(
      "place",
      "side",
      "front",
      "top",
      "bottom",
      "middle",
      "end",
      "edge",
      "corner",
      "inside",
      "outside",
      "north",
      "south",
      "east",
      "west",
      "right",
      "left",
      "way",
      "border",
      "centre",
      "entrance",
      "above",
      "below",
      "near",
      "far",
    ),
  },
  {
    id: "unit-37-colours-and-shapes",
    order: 37,
    title: "More colours & shapes",
    words: adjectives(
      "purple",
      "dark",
      "bright",
      "round",
      "flat",
      "straight",
      "crooked",
      "deep",
      "thick",
      "thin",
      "sharp",
      "blunt",
      "smooth",
      "rough",
      "curved",
      "pointed",
      "spotted",
      "striped",
    ),
  },
  {
    id: "unit-38-abstract",
    order: 38,
    title: "Ideas & feelings",
    words: nouns(
      "anger",
      "joy",
      "peace",
      "war",
      "truth",
      "shame",
      "pride",
      "patience",
      "courage",
      "kindness",
      "respect",
      "trouble",
      "problem",
      "luck",
      "fortune",
      "wisdom",
      "power",
      "freedom",
      "justice",
      "law",
      "duty",
    ),
  },
];
