/**
 * The curriculum is authored here, not derived from a dictionary: the choice
 * of which words a child learns first is a teaching decision. The drafter
 * looks each English word up in the lexicon and proposes Oromo answers for a
 * fluent speaker to confirm.
 */
export interface UnitSpec {
  id: string;
  order: number;
  title: string;
  /** English prompts, in teaching order. `pos` narrows lexicon candidates. */
  words: { english: string; pos: "noun" | "verb" | "adj" | "num" }[];
}

type Pos = UnitSpec["words"][number]["pos"];

const of =
  (pos: Pos) =>
  (...words: string[]): UnitSpec["words"] =>
    words.map((english) => ({ english, pos }));

const nouns = of("noun");
const verbs = of("verb");
const adjectives = of("adj");
const numbers = of("num");

export const UNITS: UnitSpec[] = [
  {
    id: "unit-01-family",
    order: 1,
    title: "Family",
    words: nouns(
      "mother",
      "father",
      "child",
      "baby",
      "brother",
      "sister",
      "son",
      "daughter",
      "grandmother",
      "grandfather",
      "family",
      "boy",
      "girl",
      "man",
      "woman",
      "friend",
      "name",
      "home",
      "husband",
      "wife",
      "uncle",
      "aunt",
      "people",
      "neighbor",
      "guest",
    ),
  },
  {
    id: "unit-02-food-and-drink",
    order: 2,
    title: "Food & drink",
    words: [
      ...nouns(
        "water",
        "milk",
        "coffee",
        "tea",
        "bread",
        "meat",
        "egg",
        "salt",
        "sugar",
        "butter",
        "honey",
        "food",
        "fruit",
        "banana",
        "orange",
        "onion",
        "potato",
        "maize",
        "barley",
        "porridge",
        "cup",
        "plate",
        "spoon",
      ),
      ...verbs("eat", "drink"),
    ],
  },
  {
    id: "unit-03-animals",
    order: 3,
    title: "Animals",
    words: nouns(
      "dog",
      "cat",
      "cow",
      "ox",
      "goat",
      "sheep",
      "horse",
      "donkey",
      "camel",
      "chicken",
      "bird",
      "fish",
      "lion",
      "elephant",
      "monkey",
      "snake",
      "mouse",
      "hyena",
      "leopard",
      "buffalo",
      "bee",
      "fly",
      "hen",
      "calf",
      "animal",
    ),
  },
  {
    id: "unit-04-numbers",
    order: 4,
    title: "Numbers & counting",
    words: [
      ...numbers(
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "twenty",
        "thirty",
        "fifty",
        "hundred",
        "thousand",
        "first",
        "second",
        "third",
      ),
      ...nouns("number", "half"),
      ...adjectives("many", "few"),
      ...verbs("count"),
    ],
  },
  {
    id: "unit-05-colours-and-sizes",
    order: 5,
    title: "Colours & sizes",
    words: [
      ...adjectives(
        "red",
        "white",
        "black",
        "green",
        "yellow",
        "blue",
        "brown",
        "grey",
        "big",
        "small",
        "long",
        "short",
        "tall",
        "wide",
        "narrow",
        "heavy",
        "light",
        "new",
        "old",
        "hot",
        "cold",
        "clean",
        "dirty",
      ),
      ...nouns("colour", "size"),
    ],
  },
  {
    id: "unit-06-feelings-and-doing",
    order: 6,
    title: "Feelings & doing",
    words: [
      ...adjectives(
        "happy",
        "sad",
        "angry",
        "tired",
        "hungry",
        "thirsty",
        "sick",
        "afraid",
        "good",
        "bad",
      ),
      ...verbs(
        "play",
        "sleep",
        "run",
        "walk",
        "sit",
        "stand",
        "come",
        "go",
        "speak",
        "hear",
        "see",
        "read",
        "write",
        "laugh",
        "cry",
      ),
    ],
  },
  {
    id: "unit-07-body",
    order: 7,
    title: "Body",
    words: nouns(
      "head",
      "hair",
      "eye",
      "ear",
      "nose",
      "mouth",
      "tooth",
      "tongue",
      "lip",
      "neck",
      "shoulder",
      "arm",
      "hand",
      "finger",
      "nail",
      "chest",
      "heart",
      "back",
      "stomach",
      "belly",
      "leg",
      "knee",
      "foot",
      "toe",
      "skin",
    ),
  },
  {
    id: "unit-08-health",
    order: 8,
    title: "Health & feeling unwell",
    words: nouns(
      "illness",
      "pain",
      "fever",
      "cough",
      "wound",
      "medicine",
      "doctor",
      "hospital",
      "nurse",
      "blood",
      "health",
      "sneeze",
      "headache",
      "thirst",
      "hunger",
      "dream",
      "scar",
      "sickness",
      "cure",
      "vomit",
      "injury",
      "swelling",
      "itch",
      "death",
      "life",
    ),
  },
  {
    id: "unit-09-clothes",
    order: 9,
    title: "Clothes",
    words: nouns(
      "clothes",
      "shirt",
      "trousers",
      "dress",
      "skirt",
      "shoe",
      "hat",
      "cap",
      "belt",
      "coat",
      "blanket",
      "cloth",
      "cotton",
      "wool",
      "button",
      "pocket",
      "ring",
      "necklace",
      "bracelet",
      "earring",
      "needle",
      "thread",
      "scarf",
      "towel",
      "bead",
    ),
  },
  {
    id: "unit-10-house",
    order: 10,
    title: "House & home",
    words: nouns(
      "house",
      "door",
      "window",
      "roof",
      "wall",
      "floor",
      "room",
      "bed",
      "chair",
      "table",
      "lamp",
      "key",
      "fence",
      "gate",
      "yard",
      "kitchen",
      "garden",
      "stairs",
      "shelf",
      "box",
      "basket",
      "bag",
      "broom",
      "mat",
      "curtain",
    ),
  },
  {
    id: "unit-11-kitchen",
    order: 11,
    title: "Kitchen & utensils",
    words: nouns(
      "pot",
      "pan",
      "knife",
      "fork",
      "bowl",
      "bottle",
      "jug",
      "kettle",
      "lid",
      "cover",
      "firewood",
      "oven",
      "flour",
      "oil",
      "cheese",
      "spice",
      "pepper",
      "soup",
    ),
  },
  {
    id: "unit-12-school",
    order: 12,
    title: "School & learning",
    words: nouns(
      "school",
      "teacher",
      "student",
      "book",
      "page",
      "pen",
      "pencil",
      "paper",
      "letter",
      "word",
      "question",
      "answer",
      "lesson",
      "story",
      "song",
      "language",
      "chalk",
      "class",
      "library",
      "pupil",
      "knowledge",
      "writing",
      "reading",
      "game",
      "rule",
    ),
  },
  {
    id: "unit-13-time",
    order: 13,
    title: "Time, days & seasons",
    words: nouns(
      "time",
      "day",
      "night",
      "morning",
      "evening",
      "afternoon",
      "week",
      "month",
      "year",
      "today",
      "tomorrow",
      "hour",
      "minute",
      "season",
      "summer",
      "winter",
      "spring",
      "autumn",
      "rain",
      "sun",
      "moon",
      "star",
      "sky",
      "dawn",
      "dusk",
    ),
  },
  {
    id: "unit-14-weather",
    order: 14,
    title: "Weather & sky",
    words: nouns(
      "wind",
      "cloud",
      "storm",
      "thunder",
      "lightning",
      "heat",
      "ice",
      "fog",
      "dew",
      "rainbow",
      "shade",
      "drought",
      "flood",
      "mud",
      "dust",
      "smoke",
      "air",
      "darkness",
      "frost",
      "weather",
    ),
  },
  {
    id: "unit-15-nature",
    order: 15,
    title: "Land & water",
    words: nouns(
      "land",
      "mountain",
      "hill",
      "valley",
      "river",
      "stream",
      "lake",
      "sea",
      "well",
      "stone",
      "rock",
      "sand",
      "soil",
      "forest",
      "field",
      "farm",
      "road",
      "path",
      "bridge",
      "cave",
      "island",
      "shore",
      "desert",
      "grass",
      "hole",
    ),
  },
  {
    id: "unit-16-plants",
    order: 16,
    title: "Trees & plants",
    words: nouns(
      "tree",
      "leaf",
      "branch",
      "root",
      "flower",
      "seed",
      "bush",
      "thorn",
      "bark",
      "wood",
      "trunk",
      "plant",
      "crop",
      "weed",
      "stem",
      "shoot",
      "vine",
      "bamboo",
      "palm",
      "cactus",
      "moss",
      "pollen",
    ),
  },
  {
    id: "unit-17-fruit",
    order: 17,
    title: "Fruit & vegetables",
    words: nouns(
      "lemon",
      "mango",
      "apple",
      "papaya",
      "pineapple",
      "tomato",
      "garlic",
      "cabbage",
      "carrot",
      "pumpkin",
      "bean",
      "pea",
      "corn",
      "wheat",
      "sorghum",
      "rice",
      "spinach",
      "melon",
    ),
  },
  {
    id: "unit-18-cooking",
    order: 18,
    title: "Cooking & meals",
    words: nouns(
      "meal",
      "lunch",
      "supper",
      "dinner",
      "stew",
      "sauce",
      "dough",
      "juice",
      "beer",
      "taste",
      "cream",
      "fat",
      "broth",
      "mash",
      "slice",
      "loaf",
      "grain",
      "husk",
      "peel",
      "yeast",
      "portion",
      "leftovers",
      "feast",
      "snack",
      "cake",
    ),
  },
  {
    id: "unit-19-livestock",
    order: 19,
    title: "Farm animals",
    words: nouns(
      "bull",
      "lamb",
      "mule",
      "rooster",
      "chick",
      "pig",
      "rabbit",
      "herd",
      "cattle",
      "horn",
      "hoof",
      "shepherd",
      "barn",
      "pasture",
      "manure",
      "fodder",
      "graze",
      "kid",
      "ewe",
      "ram",
      "stallion",
      "mare",
      "flock",
      "cage",
      "saddle",
    ),
  },
  {
    id: "unit-20-wild-animals",
    order: 20,
    title: "Wild animals",
    words: nouns(
      "giraffe",
      "zebra",
      "baboon",
      "antelope",
      "gazelle",
      "rhinoceros",
      "hippopotamus",
      "crocodile",
      "lizard",
      "frog",
      "fox",
      "jackal",
      "wolf",
      "bear",
      "deer",
      "porcupine",
      "squirrel",
      "bat",
      "rat",
      "mole",
    ),
  },
  {
    id: "unit-21-birds",
    order: 21,
    title: "Birds",
    words: nouns(
      "duck",
      "goose",
      "dove",
      "pigeon",
      "crow",
      "eagle",
      "hawk",
      "vulture",
      "owl",
      "ostrich",
      "stork",
      "parrot",
      "sparrow",
      "swallow",
      "nest",
      "wing",
      "feather",
      "beak",
      "claw",
      "tail",
      "flight",
      "heron",
      "falcon",
    ),
  },
  {
    id: "unit-22-insects",
    order: 22,
    title: "Insects & small creatures",
    words: nouns(
      "insect",
      "mosquito",
      "wasp",
      "ant",
      "termite",
      "spider",
      "web",
      "scorpion",
      "butterfly",
      "locust",
      "grasshopper",
      "beetle",
      "worm",
      "snail",
      "flea",
      "louse",
      "tick",
      "caterpillar",
      "cricket",
      "sting",
      "larva",
    ),
  },
  {
    id: "unit-23-market",
    order: 23,
    title: "Market & money",
    words: nouns(
      "market",
      "money",
      "price",
      "shop",
      "trade",
      "coin",
      "silver",
      "gold",
      "change",
      "debt",
      "loan",
      "profit",
      "loss",
      "wealth",
      "poverty",
      "scale",
      "weight",
      "measure",
      "sack",
      "customer",
      "goods",
      "work",
      "wage",
      "tax",
      "gift",
    ),
  },
  {
    id: "unit-24-town",
    order: 24,
    title: "Town & buildings",
    words: nouns(
      "town",
      "city",
      "village",
      "street",
      "church",
      "mosque",
      "office",
      "hotel",
      "station",
      "bank",
      "post",
      "prison",
      "court",
      "palace",
      "square",
      "building",
      "camp",
      "compound",
    ),
  },
  {
    id: "unit-25-travel",
    order: 25,
    title: "Travel & transport",
    words: nouns(
      "journey",
      "car",
      "bus",
      "truck",
      "bicycle",
      "wheel",
      "cart",
      "train",
      "boat",
      "ship",
      "canoe",
      "ticket",
      "passenger",
      "distance",
      "direction",
      "map",
      "speed",
      "stop",
      "departure",
    ),
  },
  {
    id: "unit-26-work",
    order: 26,
    title: "Work & jobs",
    words: nouns(
      "farmer",
      "soldier",
      "police",
      "judge",
      "king",
      "queen",
      "chief",
      "servant",
      "guard",
      "fisherman",
      "blacksmith",
      "carpenter",
      "tailor",
      "weaver",
      "potter",
      "singer",
      "priest",
      "leader",
      "helper",
      "worker",
      "cook",
      "baker",
    ),
  },
  {
    id: "unit-27-tools",
    order: 27,
    title: "Tools & materials",
    words: nouns(
      "tool",
      "axe",
      "hoe",
      "rope",
      "string",
      "hammer",
      "saw",
      "stick",
      "spear",
      "bow",
      "arrow",
      "shield",
      "gun",
      "net",
      "trap",
      "plough",
      "yoke",
      "iron",
      "metal",
      "glass",
      "clay",
      "leather",
      "plastic",
    ),
  },
  {
    id: "unit-28-culture",
    order: 28,
    title: "Music, story & celebration",
    words: nouns(
      "music",
      "drum",
      "flute",
      "dance",
      "riddle",
      "proverb",
      "poem",
      "wedding",
      "funeral",
      "ceremony",
      "blessing",
      "prayer",
      "god",
      "spirit",
      "custom",
      "tradition",
      "clan",
      "elder",
      "holiday",
    ),
  },
  {
    id: "unit-29-verbs-move",
    order: 29,
    title: "Verbs: moving",
    words: verbs(
      "jump",
      "climb",
      "fall",
      "lie",
      "enter",
      "leave",
      "return",
      "arrive",
      "follow",
      "flee",
      "carry",
      "bring",
      "send",
      "push",
      "pull",
      "turn",
      "cross",
      "swim",
      "ride",
      "pass",
      "wait",
      "hurry",
      "travel",
      "crawl",
    ),
  },
  {
    id: "unit-30-verbs-speak",
    order: 30,
    title: "Verbs: speaking & thinking",
    words: verbs(
      "say",
      "tell",
      "ask",
      "call",
      "shout",
      "whisper",
      "sing",
      "think",
      "know",
      "understand",
      "remember",
      "forget",
      "learn",
      "teach",
      "believe",
      "want",
      "hope",
      "fear",
      "love",
      "hate",
      "decide",
      "promise",
      "greet",
      "thank",
      "pray",
    ),
  },
  {
    id: "unit-31-verbs-hands",
    order: 31,
    title: "Verbs: hands & making",
    words: verbs(
      "take",
      "give",
      "hold",
      "put",
      "open",
      "close",
      "tie",
      "cut",
      "break",
      "build",
      "make",
      "dig",
      "sow",
      "harvest",
      "grind",
      "pound",
      "sew",
      "weave",
      "wash",
      "sweep",
      "bake",
      "boil",
      "fill",
      "pour",
      "throw",
    ),
  },
  {
    id: "unit-32-verbs-body",
    order: 32,
    title: "Verbs: body & senses",
    words: verbs(
      "wake",
      "listen",
      "smell",
      "touch",
      "feel",
      "breathe",
      "bite",
      "chew",
      "spit",
      "bathe",
      "rest",
      "die",
      "grow",
      "heal",
      "yawn",
      "blink",
      "shiver",
      "sweat",
      "tremble",
      "kneel",
      "bend",
      "stretch",
      "swell",
      "bleed",
      "faint",
    ),
  },
  {
    id: "unit-33-verbs-daily",
    order: 33,
    title: "Verbs: everyday life",
    words: verbs(
      "help",
      "buy",
      "sell",
      "pay",
      "borrow",
      "lend",
      "keep",
      "find",
      "lose",
      "search",
      "choose",
      "share",
      "divide",
      "add",
      "begin",
      "finish",
      "try",
      "use",
      "need",
      "show",
      "hide",
      "meet",
      "visit",
      "live",
      "stay",
    ),
  },
  {
    id: "unit-34-adjectives",
    order: 34,
    title: "Describing things",
    words: adjectives(
      "young",
      "large",
      "strong",
      "weak",
      "full",
      "empty",
      "warm",
      "sweet",
      "bitter",
      "sour",
      "soft",
      "hard",
      "fast",
      "slow",
      "beautiful",
      "ugly",
      "rich",
      "poor",
      "easy",
      "difficult",
    ),
  },
  {
    id: "unit-35-people",
    order: 35,
    title: "People & community",
    words: nouns(
      "person",
      "youth",
      "stranger",
      "neighbour",
      "enemy",
      "tribe",
      "nation",
      "relative",
      "orphan",
      "widow",
      "bride",
      "groom",
      "twin",
      "group",
      "citizen",
      "ancestor",
      "descendant",
      "generation",
      "age",
      "couple",
      "company",
      "assembly",
      "meeting",
      "quarrel",
      "agreement",
    ),
  },
  {
    id: "unit-36-directions",
    order: 36,
    title: "Places & directions",
    words: nouns(
      "place",
      "side",
      "front",
      "top",
      "bottom",
      "middle",
      "end",
      "edge",
      "corner",
      "inside",
      "outside",
      "north",
      "south",
      "east",
      "west",
      "right",
      "left",
      "way",
      "border",
      "centre",
      "entrance",
      "above",
      "below",
      "near",
      "far",
    ),
  },
  {
    id: "unit-37-colours-and-shapes",
    order: 37,
    title: "More colours & shapes",
    words: adjectives(
      "purple",
      "dark",
      "bright",
      "round",
      "flat",
      "straight",
      "crooked",
      "deep",
      "thick",
      "thin",
      "sharp",
      "blunt",
      "smooth",
      "rough",
      "curved",
      "pointed",
      "spotted",
      "striped",
    ),
  },
  {
    id: "unit-38-abstract",
    order: 38,
    title: "Ideas & feelings",
    words: nouns(
      "anger",
      "joy",
      "peace",
      "war",
      "truth",
      "shame",
      "pride",
      "patience",
      "courage",
      "kindness",
      "respect",
      "trouble",
      "problem",
      "luck",
      "fortune",
      "wisdom",
      "power",
      "freedom",
      "justice",
      "law",
      "duty",
    ),
  },
  {
    id: "unit-39-describing-more",
    order: 39,
    title: "Describing people & things",
    words: adjectives(
      "slim",
      "brave",
      "shy",
      "clever",
      "lazy",
      "cruel",
      "proud",
      "handsome",
      "tender",
      "delicious",
      "eager",
      "foolish",
      "evil",
      "visible",
      "alive",
      "lean",
      "younger",
    ),
  },
  {
    id: "unit-40-verbs-senses",
    order: 40,
    title: "Verbs: senses & noticing",
    words: verbs(
      "look",
      "watch",
      "notice",
      "observe",
      "ache",
      "hurt",
      "inspect",
      "glimpse",
      "sniff",
      "lick",
      "vibrate",
      "shine",
      "glitter",
      "echo",
    ),
  },
  {
    id: "unit-41-classroom",
    order: 41,
    title: "Classroom & study",
    words: nouns(
      "notebook",
      "dictionary",
      "exercise",
      "example",
      "quiz",
      "mathematics",
      "subject",
      "grade",
      "certificate",
      "education",
      "instruction",
      "instructor",
      "chart",
      "diagram",
      "alphabet",
      "folder",
      "marker",
      "note",
      "examination",
      "discipline",
      "schedule",
      "curriculum",
      "register",
      "dormitory",
      "campus",
    ),
  },
  {
    id: "unit-42-reading-writing",
    order: 42,
    title: "Reading & writing",
    words: nouns(
      "grammar",
      "spelling",
      "vowel",
      "syllable",
      "phrase",
      "translation",
      "chapter",
      "novel",
      "poetry",
      "author",
      "print",
      "comma",
      "apostrophe",
      "prefix",
      "suffix",
      "idiom",
      "adjective",
      "pronoun",
      "punctuation",
      "synonym",
      "glossary",
      "footnote",
      "stanza",
      "sketch",
      "manuscript",
    ),
  },
  {
    id: "unit-43-shapes-measuring",
    order: 43,
    title: "Numbers, shapes & measuring",
    words: nouns(
      "circle",
      "triangle",
      "rectangle",
      "oval",
      "sphere",
      "cone",
      "cylinder",
      "line",
      "dot",
      "length",
      "width",
      "height",
      "depth",
      "measurement",
      "digit",
      "fraction",
      "total",
      "sum",
      "quantity",
      "amount",
      "pair",
      "percent",
    ),
  },
  {
    id: "unit-44-furniture",
    order: 44,
    title: "Furniture & household things",
    words: nouns(
      "mattress",
      "pillow",
      "drawer",
      "sofa",
      "stool",
      "carpet",
      "rug",
      "mirror",
      "candle",
      "bucket",
      "lock",
      "ceiling",
      "hearth",
      "fireplace",
      "pillar",
      "porch",
      "courtyard",
      "wallpaper",
      "hook",
      "peg",
      "mop",
      "bin",
      "tray",
      "container",
      "cottage",
    ),
  },
  {
    id: "unit-45-keeping-clean",
    order: 45,
    title: "Washing & keeping clean",
    words: nouns(
      "soap",
      "comb",
      "razor",
      "scissors",
      "toilet",
      "shower",
      "sponge",
      "cleanliness",
      "dirt",
      "rubbish",
      "garbage",
      "washing",
      "bathing",
      "perfume",
      "faucet",
      "sieve",
      "polishing",
      "purification",
      "apron",
      "diaper",
      "pajamas",
      "wax",
      "filter",
      "filtration",
      "washer",
    ),
  },
  {
    id: "unit-46-clothes-more",
    order: 46,
    title: "Clothes & things we wear",
    words: nouns(
      "jacket",
      "sweater",
      "socks",
      "sandals",
      "boot",
      "gloves",
      "underwear",
      "vest",
      "uniform",
      "zip",
      "collar",
      "lace",
      "purse",
      "wallet",
      "umbrella",
      "garment",
      "silk",
      "flannel",
      "embroidery",
      "veil",
      "sheath",
      "stocking",
      "accessories",
      "badge",
    ),
  },
  {
    id: "unit-47-food-more",
    order: 47,
    title: "Food & flavours",
    words: nouns(
      "yogurt",
      "pasta",
      "salad",
      "sandwich",
      "pancake",
      "popcorn",
      "oats",
      "vinegar",
      "mustard",
      "ingredient",
      "bacon",
      "cinnamon",
      "cumin",
      "syrup",
      "mushroom",
      "malt",
      "flavor",
      "relish",
      "edible",
      "boiled",
      "toasted",
      "mouthful",
    ),
  },
  {
    id: "unit-48-fruit-more",
    order: 48,
    title: "More fruit & vegetables",
    words: nouns(
      "lime",
      "peach",
      "watermelon",
      "coconut",
      "peas",
      "ginger",
      "chili",
      "fruits",
      "vegetable",
      "beet",
      "berry",
      "peanut",
      "soybean",
      "rye",
      "seedlings",
      "stalk",
      "ripe",
      "harvesting",
      "compost",
      "fertile",
    ),
  },
  {
    id: "unit-49-drinks-sweets",
    order: 49,
    title: "Drinks & sweet things",
    words: nouns(
      "wine",
      "sweetness",
      "straw",
      "flask",
      "jar",
      "beverage",
      "brewer",
      "brewery",
      "whey",
      "sip",
      "canteen",
      "pitcher",
      "funnel",
      "steam",
      "fermented",
    ),
  },
  {
    id: "unit-50-celebrations",
    order: 50,
    title: "Birthdays & celebrations",
    words: nouns(
      "birthday",
      "celebration",
      "festival",
      "marriage",
      "party",
      "guests",
      "present",
      "christmas",
      "valentine",
      "anniversary",
      "invitation",
      "greeting",
      "crown",
      "photograph",
      "picture",
      "memory",
      "coronation",
      "commemoration",
      "decoration",
      "lullaby",
      "chanting",
      "celebrating",
      "enjoyment",
      "entertainment",
      "ornament",
    ),
  },
  {
    id: "unit-51-face-head",
    order: 51,
    title: "Body: face & head",
    words: nouns(
      "face",
      "forehead",
      "cheek",
      "chin",
      "jaw",
      "eyelash",
      "nostril",
      "gum",
      "throat",
      "beard",
      "moustache",
      "mustache",
      "skull",
      "brain",
      "wrinkle",
      "smile",
      "tear",
      "eyeball",
      "eyelashes",
      "palate",
      "curl",
      "tattoo",
      "scent",
    ),
  },
  {
    id: "unit-52-limbs-bones",
    order: 52,
    title: "Body: arms, legs & bones",
    words: nouns(
      "elbow",
      "thumb",
      "knuckle",
      "hip",
      "thigh",
      "ankle",
      "heel",
      "bone",
      "spine",
      "joint",
      "muscle",
      "tendon",
      "ligament",
      "waist",
      "armpit",
      "buttocks",
      "pelvis",
      "calves",
      "fist",
      "abdomen",
      "posture",
      "stride",
    ),
  },
  {
    id: "unit-53-organs",
    order: 53,
    title: "Body inside",
    words: nouns(
      "lung",
      "liver",
      "kidney",
      "intestine",
      "bladder",
      "womb",
      "artery",
      "breath",
      "gland",
      "hormone",
      "cell",
      "saliva",
      "urine",
      "marrow",
      "bowels",
      "embryo",
      "mucus",
      "diaphragm",
      "oxygen",
      "vessel",
      "lobe",
    ),
  },
  {
    id: "unit-54-illness",
    order: 54,
    title: "Illness & medicine",
    words: nouns(
      "bruise",
      "blister",
      "allergy",
      "infection",
      "disease",
      "malaria",
      "measles",
      "diarrhea",
      "nausea",
      "vomiting",
      "pill",
      "vaccine",
      "syringe",
      "plaster",
      "healing",
      "eczema",
      "epilepsy",
      "migraine",
      "rabies",
      "leprosy",
      "diarrhoea",
      "poisoning",
      "antidote",
      "vaccination",
      "coughing",
    ),
  },
  {
    id: "unit-55-clinic",
    order: 55,
    title: "Doctor, clinic & safety",
    words: nouns(
      "midwife",
      "physician",
      "patient",
      "clinic",
      "pharmacy",
      "laboratory",
      "accident",
      "safety",
      "helmet",
      "warning",
      "inspection",
      "diet",
      "care",
      "advice",
      "appointment",
      "dentist",
      "examiner",
      "inspector",
      "rehabilitation",
      "prevention",
      "precaution",
      "readiness",
      "assistance",
      "guidance",
      "shelter",
    ),
  },
  {
    id: "unit-56-feelings-happy",
    order: 56,
    title: "Feelings: happy & sad",
    words: nouns(
      "happiness",
      "pleasure",
      "delight",
      "laughter",
      "comfort",
      "friendship",
      "sorrow",
      "grief",
      "loneliness",
      "misery",
      "disappointment",
      "regret",
      "longing",
      "mood",
      "feeling",
      "emotion",
      "relief",
      "hopeful",
      "closeness",
      "fun",
      "amazement",
      "affectionate",
      "goodness",
    ),
  },
  {
    id: "unit-57-feelings-fear",
    order: 57,
    title: "Feelings: fear, anger & calm",
    words: nouns(
      "terror",
      "horror",
      "panic",
      "worry",
      "anxiety",
      "shock",
      "hatred",
      "jealousy",
      "envy",
      "revenge",
      "grudge",
      "silence",
      "bravery",
      "surprise",
      "anguish",
      "despair",
      "distress",
      "remorse",
      "bitterness",
      "enmity",
      "hostility",
      "humiliation",
      "disgust",
      "suspicion",
      "hesitation",
    ),
  },
  {
    id: "unit-58-character",
    order: 58,
    title: "Character & manners",
    words: nouns(
      "generosity",
      "gentleness",
      "politeness",
      "obedience",
      "cleverness",
      "laziness",
      "arrogance",
      "selfishness",
      "cruelty",
      "coward",
      "liar",
      "thief",
      "fool",
      "idiot",
      "bully",
      "manner",
      "habit",
      "cunning",
      "dignity",
      "generous",
      "foolishness",
      "stupidity",
      "timid",
      "careless",
      "sincerity",
    ),
  },
  {
    id: "unit-59-relatives",
    order: 59,
    title: "Family & relatives",
    words: nouns(
      "cousin",
      "sibling",
      "siblings",
      "stepfather",
      "stepmother",
      "infant",
      "toddler",
      "youngster",
      "teenager",
      "adult",
      "spouse",
      "homestead",
      "kinship",
      "genealogy",
      "dowry",
      "fiance",
      "fiancee",
      "bachelor",
      "mothers",
      "parenthood",
      "infancy",
      "adolescence",
      "maternity",
    ),
  },
  {
    id: "unit-60-friends",
    order: 60,
    title: "Friends & getting along",
    words: nouns(
      "team",
      "visitor",
      "conversation",
      "talk",
      "secret",
      "trust",
      "argument",
      "apology",
      "forgiveness",
      "comrade",
      "follower",
      "guardian",
      "keeper",
      "hostess",
      "welcoming",
      "gossip",
      "reconciliation",
      "disagreement",
      "betrayal",
      "collaborator",
      "participant",
      "member",
      "membership",
    ),
  },
  {
    id: "unit-61-sky",
    order: 61,
    title: "Sky, sun & stars",
    words: nouns(
      "sunrise",
      "sunset",
      "daytime",
      "midnight",
      "twilight",
      "shadow",
      "eclipse",
      "planet",
      "universe",
      "galaxy",
      "space",
      "orbit",
      "horizon",
      "asteroid",
      "zenith",
      "equinox",
      "hemisphere",
      "altitude",
      "latitude",
      "globe",
      "glimmer",
      "glowing",
      "midday",
    ),
  },
  {
    id: "unit-62-weather-more",
    order: 62,
    title: "Weather & seasons",
    words: nouns(
      "drizzle",
      "whirlwind",
      "tornado",
      "cloudy",
      "windy",
      "rainy",
      "climate",
      "forecast",
      "moisture",
      "evaporation",
      "chill",
      "warming",
      "cooling",
      "earthquake",
      "erosion",
      "tropics",
      "dried",
    ),
  },
  {
    id: "unit-63-water",
    order: 63,
    title: "Rivers, lakes & sea",
    words: nouns(
      "pond",
      "puddle",
      "ocean",
      "bay",
      "beach",
      "wave",
      "waterfall",
      "dam",
      "canal",
      "swamp",
      "marsh",
      "harbor",
      "tributary",
      "catchment",
      "delta",
      "gully",
      "ditch",
      "oasis",
      "glacier",
      "leakage",
      "pipe",
      "dive",
    ),
  },
  {
    id: "unit-64-land",
    order: 64,
    title: "Mountains & land",
    words: nouns(
      "highland",
      "canyon",
      "gorge",
      "plain",
      "plateau",
      "jungle",
      "wilderness",
      "boulder",
      "pebble",
      "ground",
      "ridge",
      "peak",
      "slope",
      "topography",
      "peninsula",
      "meadow",
      "hollow",
      "mound",
      "trench",
      "terrace",
      "boundary",
      "landscape",
      "cavity",
    ),
  },
  {
    id: "unit-65-plants-more",
    order: 65,
    title: "Trees, flowers & grass",
    words: nouns(
      "bough",
      "petal",
      "seeds",
      "shrub",
      "timber",
      "fern",
      "lily",
      "clover",
      "acacia",
      "eucalyptus",
      "juniper",
      "algae",
      "twig",
      "reed",
      "flax",
      "botany",
      "vegetation",
      "ebony",
      "cane",
      "resin",
    ),
  },
  {
    id: "unit-66-farm-crops",
    order: 66,
    title: "Farm & crops",
    words: nouns(
      "plow",
      "teff",
      "sugarcane",
      "fertilizer",
      "dung",
      "plantation",
      "farmland",
      "granary",
      "agriculture",
      "fertility",
      "deforestation",
      "milking",
      "grazing",
      "rations",
      "sickle",
      "hectare",
      "harness",
    ),
  },
  {
    id: "unit-67-wild-more",
    order: 67,
    title: "Wild animals",
    words: nouns(
      "tiger",
      "ape",
      "badger",
      "cub",
      "predator",
      "beast",
      "carcass",
      "jaguar",
      "panda",
      "colt",
      "cubs",
      "kitten",
      "puppy",
      "pony",
      "mules",
      "weasel",
      "scavenger",
      "venom",
      "burrow",
      "habitat",
      "mammals",
      "creature",
    ),
  },
  {
    id: "unit-68-birds-fish",
    order: 68,
    title: "Birds & fish",
    words: nouns(
      "raven",
      "peacock",
      "partridge",
      "gill",
      "whale",
      "turtle",
      "pelican",
      "quail",
      "roost",
      "wings",
      "yolk",
      "shell",
      "snare",
    ),
  },
  {
    id: "unit-69-insects-reptiles",
    order: 69,
    title: "Insects & reptiles",
    words: nouns(
      "cockroach",
      "lice",
      "cobra",
      "python",
      "chameleon",
      "dragonfly",
      "reptile",
      "mite",
      "nit",
      "leech",
      "parasite",
      "pests",
      "swarm",
    ),
  },
  {
    id: "unit-70-rocks-metals",
    order: 70,
    title: "Earth, rocks & metals",
    words: nouns(
      "gravel",
      "copper",
      "brass",
      "tin",
      "lead",
      "charcoal",
      "coal",
      "petroleum",
      "diamond",
      "crystal",
      "marble",
      "cement",
      "brick",
      "rubber",
      "wire",
      "emerald",
      "ruby",
      "ore",
      "shale",
      "magma",
      "pigment",
      "varnish",
      "chlorine",
      "nitrate",
      "mineral",
    ),
  },
  {
    id: "unit-71-town-places",
    order: 71,
    title: "Town & places",
    words: nouns(
      "hamlet",
      "suburb",
      "park",
      "restaurant",
      "hostel",
      "temple",
      "museum",
      "castle",
      "cemetery",
      "shrine",
      "stadium",
      "arena",
      "booth",
      "salon",
      "monument",
      "settlement",
      "colony",
      "fort",
    ),
  },
  {
    id: "unit-72-shops",
    order: 72,
    title: "Shops & market",
    words: nouns(
      "merchant",
      "client",
      "cashier",
      "butcher",
      "grocery",
      "discount",
      "receipt",
      "sale",
      "queue",
      "merchandise",
      "retailer",
      "supplies",
      "auction",
      "bid",
      "customs",
      "commodity",
      "stock",
      "store",
    ),
  },
  {
    id: "unit-73-money",
    order: 73,
    title: "Money & buying",
    words: nouns(
      "cent",
      "cents",
      "dollar",
      "payment",
      "credit",
      "savings",
      "budget",
      "rent",
      "fee",
      "charity",
      "capitalism",
      "deposit",
      "dividend",
      "allowance",
      "pension",
      "ransom",
      "bribe",
      "wager",
      "lottery",
      "riches",
      "prosperity",
      "expense",
      "fare",
    ),
  },
  {
    id: "unit-74-jobs-more",
    order: 74,
    title: "Jobs & work",
    words: nouns(
      "mechanic",
      "engineer",
      "lawyer",
      "policeman",
      "waiter",
      "secretary",
      "journalist",
      "reporter",
      "artist",
      "architect",
      "professor",
      "editor",
      "publisher",
      "historian",
      "economist",
      "mathematician",
      "naturalist",
      "miner",
      "tanner",
      "janitor",
      "porter",
      "admiral",
      "captain",
      "employee",
      "employer",
    ),
  },
  {
    id: "unit-75-tools-building",
    order: 75,
    title: "Tools & building",
    words: nouns(
      "blade",
      "drill",
      "bolt",
      "wrench",
      "shovel",
      "rake",
      "ladder",
      "chain",
      "paint",
      "plank",
      "screwdriver",
      "machete",
      "clippers",
      "cutter",
      "mortar",
      "wedge",
      "spindle",
      "anchor",
      "barrel",
      "plug",
      "glue",
      "cork",
      "mould",
      "apparatus",
    ),
  },
  {
    id: "unit-76-machines",
    order: 76,
    title: "Machines & vehicles",
    words: nouns(
      "taxi",
      "tractor",
      "airplane",
      "tire",
      "brake",
      "battery",
      "generator",
      "machine",
      "fan",
      "refrigerator",
      "elevator",
      "automobile",
      "dynamo",
      "propeller",
      "pedal",
      "cable",
      "mixer",
      "heater",
      "telescope",
      "microphone",
      "telegraph",
      "cassette",
      "adapter",
      "canister",
    ),
  },
  {
    id: "unit-77-travel",
    order: 77,
    title: "Travel & journeys",
    words: nouns(
      "tourist",
      "visa",
      "suitcase",
      "guide",
      "mile",
      "transit",
      "wanderer",
      "pilgrimage",
      "migration",
      "promenade",
      "escort",
      "navigation",
      "compass",
      "camping",
      "tent",
      "shortcut",
    ),
  },
  {
    id: "unit-78-directions",
    order: 78,
    title: "Roads & directions",
    words: nouns(
      "tunnel",
      "traffic",
      "pole",
      "column",
      "diagonal",
      "parallel",
      "dimension",
      "threshold",
      "gutter",
      "hinge",
      "opposite",
      "underneath",
      "range",
      "zone",
      "section",
      "placement",
      "site",
    ),
  },
  {
    id: "unit-79-phone-computer",
    order: 79,
    title: "Post, phone & computers",
    words: nouns(
      "envelope",
      "stamp",
      "parcel",
      "package",
      "mail",
      "telephone",
      "phone",
      "message",
      "radio",
      "television",
      "screen",
      "computer",
      "keyboard",
      "printer",
      "file",
      "password",
      "network",
      "database",
      "software",
      "spreadsheet",
      "keyword",
      "inbox",
      "mailbox",
      "sidebar",
      "snapshot",
    ),
  },
  {
    id: "unit-80-sport",
    order: 80,
    title: "Sport & games",
    words: nouns(
      "sport",
      "ball",
      "player",
      "match",
      "runner",
      "running",
      "jumping",
      "swimming",
      "wrestling",
      "boxing",
      "tennis",
      "hockey",
      "gymnastics",
      "skating",
      "whistle",
      "training",
      "winner",
      "prize",
      "medal",
      "doll",
      "puzzle",
      "volleyball",
      "basketball",
      "marathon",
    ),
  },
  {
    id: "unit-81-verbs-school",
    order: 81,
    title: "Verbs: learning & school",
    words: verbs(
      "study",
      "spell",
      "explain",
      "repeat",
      "practice",
      "correct",
      "calculate",
      "solve",
      "describe",
      "translate",
      "revise",
      "memorize",
      "analyse",
      "evaluate",
      "verify",
      "summarize",
      "classify",
      "differentiate",
      "instruct",
      "educate",
      "tutor",
      "edit",
      "predict",
      "prove",
      "recognize",
    ),
  },
  {
    id: "unit-82-verbs-work",
    order: 82,
    title: "Verbs: work & making",
    words: verbs(
      "create",
      "construct",
      "repair",
      "join",
      "fasten",
      "carve",
      "sharpen",
      "lift",
      "load",
      "manufacture",
      "assemble",
      "braid",
      "forge",
      "install",
      "operate",
      "arrange",
      "rearrange",
      "stack",
      "pile",
      "trim",
      "tile",
    ),
  },
  {
    id: "unit-83-verbs-talking",
    order: 83,
    title: "Verbs: talking & asking",
    words: verbs(
      "reply",
      "argue",
      "discuss",
      "agree",
      "disagree",
      "complain",
      "declare",
      "warn",
      "advise",
      "praise",
      "blame",
      "joke",
      "pronounce",
      "converse",
      "chat",
      "inform",
      "testify",
      "rebuke",
      "insult",
      "boast",
      "nag",
      "tease",
      "summon",
      "persuade",
      "convince",
    ),
  },
  {
    id: "unit-84-verbs-thinking",
    order: 84,
    title: "Verbs: thinking & feeling",
    words: verbs(
      "doubt",
      "wish",
      "plan",
      "guess",
      "wonder",
      "admire",
      "reckon",
      "presume",
      "suspect",
      "intend",
      "resolve",
      "imply",
      "assess",
      "focus",
      "pretend",
      "deny",
      "approve",
      "oppose",
      "dislike",
    ),
  },
  {
    id: "unit-85-verbs-moving",
    order: 85,
    title: "Verbs: moving & travelling",
    words: verbs(
      "drive",
      "depart",
      "approach",
      "chase",
      "escape",
      "roam",
      "wander",
      "creep",
      "sneak",
      "leap",
      "sprint",
      "march",
      "descend",
      "rise",
      "drift",
      "float",
      "soar",
      "hover",
      "plunge",
      "stumble",
      "slide",
      "slip",
    ),
  },
  {
    id: "unit-86-verbs-giving",
    order: 86,
    title: "Verbs: giving & taking",
    words: verbs(
      "receive",
      "accept",
      "refuse",
      "owe",
      "collect",
      "gather",
      "drop",
      "exchange",
      "donate",
      "deliver",
      "supply",
      "provide",
      "purchase",
      "acquire",
      "inherit",
      "forfeit",
      "surrender",
      "reserve",
      "spare",
      "fetch",
      "haul",
      "transfer",
    ),
  },
  {
    id: "unit-87-verbs-helping",
    order: 87,
    title: "Verbs: helping & caring",
    words: verbs(
      "protect",
      "defend",
      "save",
      "feed",
      "encourage",
      "support",
      "mind",
      "accompany",
      "forgive",
      "assist",
      "aid",
      "nurture",
      "soothe",
      "tend",
      "supervise",
      "uphold",
      "obey",
      "honour",
    ),
  },
  {
    id: "unit-88-verbs-cooking",
    order: 88,
    title: "Verbs: cooking & cleaning",
    words: verbs(
      "roast",
      "stir",
      "mix",
      "knead",
      "serve",
      "scrub",
      "wipe",
      "rinse",
      "dry",
      "brew",
      "churn",
      "mince",
      "sift",
      "soak",
      "sprinkle",
      "squeeze",
      "spill",
      "melt",
      "freeze",
      "burn",
      "dilute",
      "munch",
      "suck",
      "stuff",
    ),
  },
  {
    id: "unit-89-verbs-growing",
    order: 89,
    title: "Verbs: growing & farming",
    words: verbs(
      "thresh",
      "winnow",
      "breed",
      "hatch",
      "ripen",
      "blossom",
      "wither",
      "irrigate",
      "prune",
      "spray",
      "sprout",
      "fade",
      "wilt",
      "rot",
      "multiply",
      "reproduce",
      "scatter",
    ),
  },
  {
    id: "unit-90-verbs-playing",
    order: 90,
    title: "Verbs: playing & resting",
    words: verbs(
      "relax",
      "win",
      "compete",
      "celebrate",
      "clap",
      "enjoy",
      "wink",
      "hug",
      "sway",
      "roll",
      "splash",
      "entertain",
      "amaze",
      "glow",
      "wobble",
      "dribble",
    ),
  },
  {
    id: "unit-91-time-more",
    order: 91,
    title: "Time & calendar",
    words: nouns(
      "moment",
      "century",
      "monday",
      "tuesday",
      "wednesday",
      "friday",
      "future",
      "duration",
      "period",
      "phase",
      "sequence",
      "eternity",
      "eve",
      "continuation",
    ),
  },
  {
    id: "unit-92-music-art",
    order: 92,
    title: "Music, art & dance",
    words: nouns(
      "singing",
      "dancing",
      "guitar",
      "harp",
      "trumpet",
      "piano",
      "rhythm",
      "chorus",
      "stage",
      "theatre",
      "actor",
      "gallery",
      "accordion",
      "carving",
      "poster",
      "animation",
      "drama",
      "spectacle",
      "studio",
      "octave",
    ),
  },
  {
    id: "unit-93-story-book",
    order: 93,
    title: "Story, poem & book",
    words: nouns(
      "tale",
      "tales",
      "folklore",
      "rhyme",
      "newspaper",
      "magazine",
      "report",
      "bibliography",
      "catalogue",
      "pseudonym",
      "biography",
      "nonfiction",
      "revision",
      "summary",
      "preface",
    ),
  },
  {
    id: "unit-94-country",
    order: 94,
    title: "Country & government",
    words: nouns(
      "government",
      "president",
      "parliament",
      "election",
      "citizenship",
      "mayor",
      "governor",
      "flag",
      "capital",
      "region",
      "province",
      "territory",
      "monarchy",
      "empire",
      "kingdom",
      "federation",
      "constitution",
      "delegation",
      "embargo",
      "militia",
      "navy",
      "army",
      "sovereignty",
    ),
  },
  {
    id: "unit-95-right-wrong",
    order: 95,
    title: "Rules, right & wrong",
    words: nouns(
      "injustice",
      "crime",
      "robber",
      "trial",
      "witness",
      "evidence",
      "permission",
      "responsibility",
      "fairness",
      "verdict",
      "tribunal",
      "custody",
      "pardon",
      "parole",
      "defendant",
      "prosecutor",
      "jury",
      "oath",
      "testimony",
      "robbery",
      "slander",
      "conviction",
      "imprisonment",
    ),
  },
  {
    id: "unit-96-science",
    order: 96,
    title: "School subjects & science",
    words: nouns(
      "history",
      "research",
      "hypothesis",
      "observation",
      "discovery",
      "invention",
      "matter",
      "gravity",
      "magnet",
      "electricity",
      "equation",
      "denominator",
      "diameter",
      "polygon",
      "proton",
      "magnetism",
      "friction",
      "equilibrium",
      "evolution",
      "ecosystem",
      "anatomy",
      "diffusion",
      "compression",
    ),
  },
  {
    id: "unit-97-measuring",
    order: 97,
    title: "Measuring & science words",
    words: nouns(
      "metre",
      "liter",
      "ton",
      "inch",
      "pressure",
      "volume",
      "velocity",
      "density",
      "quality",
      "average",
      "sample",
      "balance",
      "kilo",
      "proportion",
      "barometer",
      "pendulum",
      "calculation",
      "accuracy",
      "magnitude",
      "frequency",
      "voltage",
    ),
  },
  {
    id: "unit-98-tradition",
    order: 98,
    title: "Religion & tradition",
    words: nouns(
      "faith",
      "religion",
      "monk",
      "nun",
      "prophet",
      "angel",
      "soul",
      "heaven",
      "sin",
      "sacrifice",
      "culture",
      "heritage",
      "taboo",
      "burial",
      "covenant",
      "apostle",
      "bishop",
      "messiah",
      "gospel",
      "worship",
      "circumcision",
      "sorcerer",
      "deity",
      "mourning",
    ),
  },
  {
    id: "unit-99-amounts",
    order: 99,
    title: "Amounts & opposites",
    words: nouns(
      "piece",
      "handful",
      "heap",
      "bundle",
      "bunch",
      "majority",
      "minority",
      "shortage",
      "difference",
      "plurality",
      "remnant",
      "leftover",
      "cluster",
      "multiple",
    ),
  },
  {
    id: "unit-100-ideas",
    order: 100,
    title: "Ideas & abstract words",
    words: nouns(
      "idea",
      "reason",
      "cause",
      "result",
      "solution",
      "choice",
      "decision",
      "chance",
      "risk",
      "difficulty",
      "progress",
      "development",
      "growth",
      "beginning",
      "order",
      "phenomenon",
      "philosophy",
      "concept",
      "criteria",
      "context",
      "contradiction",
      "distinction",
      "priority",
      "objective",
      "obligation",
    ),
  },
];
