/**
 * The curriculum is authored here, not derived from a dictionary: the choice
 * of which words a child learns first is a teaching decision. The drafter
 * looks each English word up in the lexicon and proposes Oromo answers for a
 * fluent speaker to confirm.
 */
export interface UnitSpec {
  id: string;
  order: number;
  title: string;
  /** English prompts, in teaching order. `pos` narrows lexicon candidates. */
  words: { english: string; pos: "noun" | "verb" | "adj" | "num" }[];
}

type Pos = UnitSpec["words"][number]["pos"];

const of = (pos: Pos) =>
  (...words: string[]): UnitSpec["words"] =>
    words.map((english) => ({ english, pos }));

const nouns = of("noun");
const verbs = of("verb");
const adjectives = of("adj");
const numbers = of("num");

export const UNITS: UnitSpec[] = [
  {
    id: "unit-01-family",
    order: 1,
    title: "Family",
    words: nouns(
      "mother",
      "father",
      "child",
      "baby",
      "brother",
      "sister",
      "son",
      "daughter",
      "grandmother",
      "grandfather",
      "family",
      "boy",
      "girl",
      "man",
      "woman",
      "friend",
      "name",
      "home",
      "husband",
      "wife",
      "uncle",
      "aunt",
      "people",
      "neighbor",
      "guest",
    ),
  },
  {
    id: "unit-02-food-and-drink",
    order: 2,
    title: "Food & drink",
    words: [
      ...nouns(
        "water",
        "milk",
        "coffee",
        "tea",
        "bread",
        "meat",
        "egg",
        "salt",
        "sugar",
        "butter",
        "honey",
        "food",
        "fruit",
        "banana",
        "orange",
        "onion",
        "potato",
        "maize",
        "barley",
        "porridge",
        "cup",
        "plate",
        "spoon",
      ),
      ...verbs("eat", "drink"),
    ],
  },
  {
    id: "unit-03-animals",
    order: 3,
    title: "Animals",
    words: nouns(
      "dog",
      "cat",
      "cow",
      "ox",
      "goat",
      "sheep",
      "horse",
      "donkey",
      "camel",
      "chicken",
      "bird",
      "fish",
      "lion",
      "elephant",
      "monkey",
      "snake",
      "mouse",
      "hyena",
      "leopard",
      "buffalo",
      "bee",
      "fly",
      "hen",
      "calf",
      "animal",
    ),
  },
  {
    id: "unit-04-numbers",
    order: 4,
    title: "Numbers & counting",
    words: [
      ...numbers(
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "twenty",
        "thirty",
        "fifty",
        "hundred",
        "thousand",
        "first",
        "second",
        "third",
      ),
      ...nouns("number", "half"),
      ...adjectives("many", "few"),
      ...verbs("count"),
    ],
  },
  {
    id: "unit-05-colours-and-sizes",
    order: 5,
    title: "Colours & sizes",
    words: [
      ...adjectives(
        "red",
        "white",
        "black",
        "green",
        "yellow",
        "blue",
        "brown",
        "grey",
        "big",
        "small",
        "long",
        "short",
        "tall",
        "wide",
        "narrow",
        "heavy",
        "light",
        "new",
        "old",
        "hot",
        "cold",
        "clean",
        "dirty",
      ),
      ...nouns("colour", "size"),
    ],
  },
  {
    id: "unit-06-feelings-and-doing",
    order: 6,
    title: "Feelings & doing",
    words: [
      ...adjectives(
        "happy",
        "sad",
        "angry",
        "tired",
        "hungry",
        "thirsty",
        "sick",
        "afraid",
        "good",
        "bad",
      ),
      ...verbs(
        "play",
        "sleep",
        "run",
        "walk",
        "sit",
        "stand",
        "come",
        "go",
        "speak",
        "hear",
        "see",
        "read",
        "write",
        "laugh",
        "cry",
      ),
    ],
  },
];
